// Startup
export const FETCH_STARTUP_DATA_REQUEST = 'FETCH_STARTUP_DATA_REQUEST';

// Songs
export const CREATE_SONG_REQUEST = 'CREATE_SONG_REQUEST';
export const DELETE_SONG_REQUEST = 'DELETE_SONG_REQUEST';
export const UPDATE_SONG_TITLE_REQUEST = 'UPDATE_SONG_TITLE_REQUEST';
export const UPDATE_SONG_ARTIST_REQUEST = 'UPDATE_SONG_ARTIST_REQUEST';
export const UPDATE_SONG_COMPLETION_REQUEST = 'UPDATE_SONG_COMPLETION_REQUEST';

// Takes
export const CREATE_TAKE_REQUEST = 'CREATE_TAKE_REQUEST';
export const UPDATE_TAKE_NOTES_REQUEST = 'UPDATE_TAKE_NOTES_REQUEST';
export const DELETE_TAKE_REQUEST = 'DELETE_TAKE_REQUEST';
export const UPDATE_SELECTED_TAKE_ID_REQUEST =
  'UPDATE_SELECTED_TAKE_ID_REQUEST';
export const UPDATE_TAKE_TITLE = 'UPDATE_TAKE_TITLE';

// Pages
export const UPDATE_LYRICS_REQUEST = 'UPDATE_LYRICS_REQUEST';
export const UPDATE_PAGE_INFO_REQUEST = 'UPDATE_PAGE_INFO_REQUEST';
export const FETCH_PAGE_REQUEST = 'FETCH_PAGE_REQUEST';

// Artists
export const FETCH_ARTISTS_REQUEST = 'FETCH_ARTISTS_REQUESTS';
export const ADD_ARTIST_REQUEST = 'ADD_ARTIST_REQUEST';
export const UPDATE_ARTIST_REQUEST = 'UPDATE_ARTIST_REQUEST';
export const DELETE_ARTIST_REQUEST = 'DELETE_ARTIST_REQUEST';

// Settings
export const UPDATE_SETTINGS_REQUEST = 'UPDATE_SETTINGS_REQUEST';
export const UPDATE_CLOUD_CONNECTION_REQUEST =
  'UPDATE_CLOUD_CONNECTION_REQUEST';
export const UPDATE_SYNC_SETTINGS_REQUEST = 'UPDATE_SYNC_SETTINGS_REQUEST';

// Purchases
export const UPDATE_PURCHASES_REQUEST = 'UPDATE_PURCHASES_REQUEST';
