// Startup
export const FETCH_SONGS_WITH_TAKES_REQUEST = 'FETCH_SONGS_WITH_TAKES_REQUEST';

// Songs
export const CREATE_SONG_REQUEST = 'CREATE_SONG_REQUEST';
export const DELETE_SONG_REQUEST = 'DELETE_SONG_REQUEST';
export const UPDATE_SONG_TITLE_REQUEST = 'UPDATE_SONG_TITLE_REQUEST';

// Takes
export const CREATE_TAKE_REQUEST = 'CREATE_TAKE_REQUEST';
export const UPDATE_TAKE_NOTES_REQUEST = 'UPDATE_TAKE_NOTES_REQUEST';
export const DELETE_TAKE_REQUEST = 'DELETE_TAKE_REQUEST';
export const UPDATE_SELECTED_TAKE_ID_REQUEST =
  'UPDATE_SELECTED_TAKE_ID_REQUEST';

// Pages
export const UPDATE_LYRICS_REQUEST = 'UPDATE_LYRICS_REQUEST';
export const UPDATE_PAGE_INFO_REQUEST = 'UPDATE_PAGE_INFO_REQUEST';
export const FETCH_PAGE_REQUEST = 'FETCH_PAGE_REQUEST';
