export const FETCH_SONGS_WITH_TAKES_REQUEST = 'FETCH_SONGS_WITH_TAKES_REQUEST';
export const FETCH_SONGS_WITH_TAKES_SUCCESS = 'FETCH_SONGS_WITH_TAKES_SUCCESS';
export const FETCH_SONGS_WITH_TAKES_FAILURE = 'FETCH_SONGS_WITH_TAKES_FAILURE';

export const FETCH_PAGE_REQUEST = 'FETCH_PAGE_REQUEST';

export const CREATE_SONG_REQUEST = 'CREATE_SONG_REQUEST';
export const CREATE_SONG_SUCCESS = 'CREATE_SONG_SUCCESS';
export const CREATE_SONG_FAILURE = 'CREATE_SONG_FAILURE';

export const CREATE_TAKE_REQUEST = 'CREATE_TAKE_REQUEST';
export const CREATE_TAKE_SUCCESS = 'CREATE_TAKE_SUCCESS';
export const CREATE_TAKE_FAILURE = 'CREATE_TAKE_FAILURE';

export const UPDATE_TAKE_NOTES_REQUEST = 'UPDATE_TAKE_NOTES_REQUEST';
export const UPDATE_TAKE_NOTES_SUCCESS = 'UPDATE_TAKE_NOTES_SUCCESS';
export const UPDATE_TAKE_NOTES_FAILURE = 'UPDATE_TAKE_NOTES_FAILURE';

export const UPDATE_SELECTED_TAKE_ID_REQUEST =
  'UPDATE_SELECTED_TAKE_ID_REQUEST';
export const UPDATE_SELECTED_TAKE_ID_SUCCESS =
  'UPDATE_SELECTED_TAKE_ID_SUCCESS';
export const UPDATE_SELECTED_TAKE_ID_FAILURE =
  'UPDATE_SELECTED_TAKE_ID_FAILURE';

export const UPDATE_LYRICS_REQUEST = 'UPDATE_LYRICS_REQUEST';
export const UPDATE_LYRICS_SUCCESS = 'UPDATE_LYRICS_SUCCESS';
export const UPDATE_LYRICS_FAILURE = 'UPDATE_LYRICS_FAILURE';

export const UPDATE_PAGE_INFO_REQUEST = 'UPDATE_PAGE_INFO_REQUEST';
export const UPDATE_PAGE_INFO_SUCCESS = 'UPDATE_PAGE_INFO_SUCCESS';
export const UPDATE_PAGE_INFO_FAILURE = 'UPDATE_PAGE_INFO_FAILIRE';
