export const FETCH_SONGS_WITH_TAKES_REQUEST = 'FETCH_SONGS_WITH_TAKES_REQUEST';
export const FETCH_SONGS_WITH_TAKES_SUCCESS = 'FETCH_SONGS_WITH_TAKES_SUCCESS';
export const FETCH_SONGS_WITH_TAKES_FAILURE = 'FETCH_SONGS_WITH_TAKES_FAILURE';

export const CREATE_SONG_REQUEST = 'CREATE_SONG_REQUEST';
export const CREATE_SONG_SUCCESS = 'CREATE_SONG_SUCCESS';
export const CREATE_SONG_FAILURE = 'CREATE_SONG_FAILURE';

export const CREATE_TAKE_REQUEST = 'CREATE_TAKE_REQUEST';
export const CREATE_TAKE_SUCCESS = 'CREATE_TAKE_SUCCESS';
export const CREATE_TAKE_FAILURE = 'CREATE_TAKE_FAILURE';
