name: Create development builds

jobs:
  android_development_build:
    name: Build Android
    type: build
    params:
      platform: android
      profile: development
      auto_increment: true
  ios_development_build:
    name: Build iOS
    type: build
    params:
      platform: ios
      profile: development
      auto_increment: true