export const TOGGLE_PLAYBACK = 'playback/togglePlayback';

export const MONTH_NAMES = [
  'January',
  'February',
  'March',
  'April',
  'May',
  'June',
  'July',
  'August',
  'September',
  'October',
  'November',
  'December',
];

export const KEY_SIGNATURES = [
  { label: 'C', value: 'C' },
  { label: 'G', value: 'G' },
  { label: 'D', value: 'D' },
  { label: 'A', value: 'A' },
  { label: 'E', value: 'E' },
  { label: 'B', value: 'B' },
  { label: 'F#', value: 'F#' },
  { label: 'C#', value: 'C#' },
  { label: 'F', value: 'F' },
  { label: 'B♭', value: 'B♭' },
  { label: 'E♭', value: 'E♭' },
  { label: 'A♭', value: 'A♭' },
  { label: 'D♭', value: 'D♭' },
  { label: 'Am', value: 'Am' },
  { label: 'Em', value: 'Em' },
  { label: 'Bm', value: 'Bm' },
  { label: 'F#m', value: 'F#m' },
  { label: 'C#m', value: 'C#m' },
  { label: 'G#m', value: 'G#m' },
  { label: 'D#m', value: 'D#m' },
  { label: 'Dm', value: 'Dm' },
  { label: 'Gm', value: 'Gm' },
  { label: 'Cm', value: 'Cm' },
  { label: 'Fm', value: 'Fm' },
  { label: 'B♭m', value: 'B♭m' },
  { label: 'E♭m', value: 'E♭m' },
  { label: 'A♭m', value: 'A♭m' },
];

export const TIME_SIGNATURES = [
  { label: '4/4', value: '4/4' },
  { label: '3/4', value: '3/4' },
  { label: '2/4', value: '2/4' },
  { label: '6/8', value: '6/8' },
  { label: '9/8', value: '9/8' },
  { label: '12/8', value: '12/8' },
  { label: '5/4', value: '5/4' },
  { label: '7/8', value: '7/8' },
  { label: '10/4', value: '10/4' },
  { label: '11/8', value: '11/8' },
  { label: '2/2', value: '2/2' },
];
